# YAML Configuration: Spring Boot Common properties
# reference: http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#common-application-properties
server:
  port: 9090
spring:
  application.name: rocking-the-spring-boot
